// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	testChannel: (onEvent: Channel<string>) => __TAURI_INVOKE<void>("test_channel", { onEvent }),
	getConfig: (key: string) => __TAURI_INVOKE<string | null>("get_config", { key }),
	setConfig: (key: string, value: string) => __TAURI_INVOKE<void>("set_config", { key, value }),
};

